### ISSUE TITLE
Do not pass reference DEM as an argument

### ISSUE THREAD

**Issue by bpurinton** [uw-cryo/asp_plot#38]
Users are expected to have used a Ref DEM, and we can pull the path and filename out from the metadata (orthoimage metadata, logs, etc.)

**Comment by dshean** [comment]
I think it may be best to isolate functionality requiring reference DEM from the "core" asp_plot functionality.  If the reference DEM is present in ASP output header or log (assume path hasn't changed), then can kick off additional plotting, perhaps requiring geodiff call to create difference map (and histogram).  Alternatively, can use Python-native rioxarray approach, loading, CRS matching, and differencing.  But since we know ASP is involved, maybe simplest to just call geodiff.
